version: "3.9"
services:
  api:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/scheduler?sslmode=disable
    ports:
      - "8080:8080"

  migrate:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/scheduler?sslmode=disable
    command:
      - /app/api
      - migrate

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scheduler
    ports:
      - "5432:5432"
